feat: convert to typescript
libp2p/js-libp2p-record pull request #32
Opened 2022-02-06 13:33 UTC by achingbrain

- Converts to typescript
- Only named exports
- No more CJS, only ESM
- Runs tests on all supported environments
- Adds auto-publish
- Adds dependabot

BREAKING CHANGE: switch to named exports, ESM only

2022-02-10 18:28 UTC, wemeetagain requested changes

2022-02-10 18:28 UTC, wemeetagain commented on src/index.ts
> +  static fromDeserialized (obj: Record<string, any>) {
Type this as an `IRecord`?

2022-02-11 06:57 UTC, achingbrain commented on src/index.ts
> +  static fromDeserialized (obj: Record<string, any>) {
Done!

2022-02-14 19:09 UTC, wemeetagain approved these changes

2022-02-18 14:27 UTC, merged